# Generated by Django 5.1.1 on 2024-10-18 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentplan',
            old_name='roi_percentage',
            new_name='daily_profit_rate',
        ),
        migrations.RemoveField(
            model_name='investmentplan',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='image',
            field=models.ImageField(blank=True, default='planImg.png', null=True, upload_to='investment_plan_img/'),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='userinvestment',
            name='investment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
