# Generated by Django 5.1.1 on 2025-01-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_rename_roi_percentage_investmentplan_daily_profit_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinvestment',
            old_name='investment_status',
            new_name='status',
        ),
    ]
