# Generated by Django 5.1.1 on 2025-01-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_userinvestment_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvestment',
            name='ref_code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
