# Generated by Django 5.1.1 on 2025-01-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_alter_userinvestment_ref_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinvestment',
            old_name='ref_code',
            new_name='ref_token',
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='payment_type',
            field=models.CharField(choices=[('bitcoin', 'BITCOIN'), ('ethereum', 'ETHEREUM'), ('usdt', 'USDT')], default='bitcoin', max_length=50),
        ),
    ]
