# Generated by Django 5.1.1 on 2025-02-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_alter_userinvestment_next_accrual_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='last_accrual_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
