# Generated by Django 4.2 on 2026-02-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_userinvestment_last_accrual_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='package_bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='package_bonus_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='package_bonus_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
