# Generated by Django 5.1.1 on 2024-11-02 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referral_date',
        ),
        migrations.AddField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='referral',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
