# Generated by Django 5.1.1 on 2025-01-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_remove_referral_referral_date_referral_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='referral_bonus',
            new_name='bonus',
        ),
        migrations.AddField(
            model_name='referral',
            name='bonus_status',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false'),
        ),
    ]
