# Generated by Django 5.1.1 on 2025-01-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_rename_referral_bonus_referral_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='bonus_status',
            field=models.BooleanField(default=False),
        ),
    ]
