# Generated by Django 5.1.1 on 2024-11-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payment',
            field=models.CharField(choices=[('ethereum', 'Ethereum'), ('bitcoin', 'Bitcoin'), ('usdt', 'USDT')], default='usdt', max_length=10, verbose_name='payment options'),
        ),
    ]
