# Generated by Django 5.1.1 on 2025-01-20 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_alter_userinvestment_next_accrual_date'),
        ('withdrawals', '0003_rename_payment_withdrawalrequest_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='investment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='investments.userinvestment'),
        ),
    ]
