# Generated by Django 4.2 on 2026-02-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0004_withdrawalrequest_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
